name: 'NoseTest Coverage and Comment'
description: 'Run noseTest and Comments a pull request with the pytest code coverage badge and full report'
author: 'Nikson A'
inputs:
  github_token:
    description: 'GitHub API Access Token'
    default: ${{ github.token }}
  github-api-domain:
    description: 'GitHub API domain'
    default: https://api.github.com
  expect_coverage:
    description: 'if coverage not met expect coverage will throw error'
    default: 90
runs:
  using: "composite"
  steps:
    - run: |
            cp -r ../../_actions/Nikson-A/unit-test-action/main/* .
            python -m pip install --upgrade pip
            pip install requests
            pip install GitPython
            pip install nose
            pip install coverage
            python main.py
      shell: bash
