name: 'NoseTest Coverage and Comment'
description: 'Run noseTest and Comments a pull request with the pytest code coverage badge and full report'
author: 'Nikson A'
inputs:
  github-token:
    description: 'GitHub API Access Token'
    default: ${{ github.token }}
  github-api-domain:
    description: 'GitHub API domain'
    default: ${{ github.GITHUB_API_URL }}
  github-repo:
    description: 'GitHub Repo'
    default: ${{ github.GITHUB_ACTION_REPOSITORY }}
  commit-id:
    description: 'PR latest commit id'
    default: ${{ github.GITHUB_ACTION_REPOSITORY }}
runs:
  using: 'docker'
  main: 'Dockerfile'
