name: 'NoseTest Coverage and Comment'
description: 'Run noseTest and Comments a pull request with the pytest code coverage badge and full report'
author: 'Nikson A'
inputs:
  github-token:
    description: 'GitHub API Access Token'
    default: ${{ github.token }}
  github-api-domain:
    description: 'GitHub API domain'
    default: https://api.github.com
  github-repo:
    description: 'GitHub Repo'
    default: ${{ github.event.repository.name }}
  commit-id:
    description: 'PR latest commit id'
    default: ${{ github.event.pull_request.head.sha }}
runs:
  using: "composite"
  steps:
    - run: |
            import os
            def list_files(startpath):
              for root, dirs, files in os.walk(startpath):
                level = root.replace(startpath, '').count(os.sep)
                indent = ' ' * 4 * (level)
                print('{}{}/'.format(indent, os.path.basename(root)))
                subindent = ' ' * 4 * (level + 1)
                for f in files:
                    print('{}{}'.format(subindent, f))
            print(list_files(os.getcwd() + "../")
      shell: python
